In [1]:
import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))

In [5]:
import pandas as pd
from tqdm import tqdm
from utils import combined_approaches as ca
from utils import global_strategies as gs
from utils import label_based_measures as lbm
from utils import local_single_attribute as lsa
from utils import similarity_structures as ss
from utils import top_down_data_structures as tdds
from utils import value_overlap as vo
from utils import evaluation as eval
from utils import schema_integration as si
from utils import induced_match as im

<a id="esempio-bottomup-1"></a>
<a id="esempio-bottomup-1"></a>
<a id="esempio-bottomup-1"></a>
<a id="esempio-bottomup-1"></a>
<a id="esempio-bottomup-1"></a>
<a id="esempio-bottomup-1"></a>
<a id="esempio-bottomup-1"></a>
#  esempio BottomUp 1

In [3]:
src_links = [
'http://dbgroup.ing.unimore.it/SIWS/DataIntegration/Esempi/BottomUp_2/S1.csv',
'http://dbgroup.ing.unimore.it/SIWS/DataIntegration/Esempi/BottomUp_2/S2.csv'
]

SOURCES = { 'S'+str(i+1) : pd.read_csv(link).astype(str) for i, link in enumerate(src_links) }

GoldStandard=pd.read_csv('http://dbgroup.ing.unimore.it/SIWS/DataIntegration/Esempi/BottomUp_2/GoldStandard_A.csv').astype(str)

tdds.to_GMM(GoldStandard)

SOURCE                 S1                     S2
GAT
1        [location, addr]  [location, indirizzo]
2                  [city]                 [city]
3       [name_type, name]    [nome, descrizione]
4              [telefone]             [telefono]
5                      []                 [type]

In [4]:
SOURCES['S2']

,nome,city,telefono,type,location,descrizione,indirizzo
0,les celebrites,new york city,212-484-5113,french (classic),155 w. 58th st. (212-484-5113),les celebrites,155 w. 58th st. (212-484-5113)
1,delectables,atlanta,404-681-2909,cafeterias,1 margaret mitchell sq.,delectables,1 margaret mitchell sq. (404-681-2909)
2,lutece,new york city,212-752-2225,french (classic),249 e. 50th st.,lutece,249 e. 50th st. (212-752-2225)
3,georgia grille,atlanta,404-352-3517,southwestern,2290 peachtree rd. (404-352-3517),georgia grille,2290 peachtree rd. (404-352-3517)
4,plumpjack cafe,san francisco,415-563-4755,american (new),3127 fillmore st. (415-563-4755),plumpjack cafe,3127 fillmore st. (415-563-4755)
5,yujean kangs,pasadena,818-585-0855,chinese,67 n. raymond ave. (pasadena),yujean kangs,67 n. raymond ave. (818-585-0855)
6,phnom penh cambodian restaurant,san francisco,415-775-5979,cambodian,631 larkin st. (415-775-5979),phnom penh cambodian restaurant,631 larkin st. (415-775-5979)
7,island spice,new york city,212-765-1737,caribbean,402 w. 44th st. (212-765-1737),island spice (caribbean),402 w. 44th st.
8,sallys cafe & bakery,san francisco,415-626-6006,american,300 de haro st. (415-626-6006),sallys cafe & bakery,300 de haro st. (415-626-6006)
9,dotties true blue cafe,san francisco,415-885-2767,diners,522 jones st. (san francisco),dotties true blue cafe,522 jones st. (415-885-2767)
10,grill the,beverly hills,310-276-0615,american (traditional),9560 dayton way (beverly hills),grill the,9560 dayton way (310-276-0615)
11,thai house cafe,new york city,212-334-1085,thai,151 hudson st. (212-334-1085),thai house cafe,151 hudson st. (212-334-1085)
12,jans family restaurant,la,213-651-2866,coffee shops,8424 beverly blvd. (213-651-2866),jans family restaurant (coffee shops),8424 beverly blvd. (213-651-2866)
13,spago (los angeles),w. hollywood,310-652-4025,californian,8795 sunset blvd. (310-652-4025),spago (los angeles),8795 sunset blvd. (310-652-4025)
14,mesa grill,new york city,212-807-7400,southwestern,102 fifth ave. (new york city),mesa grill,102 fifth ave. (212-807-7400)
15,felidia,new york city,212-758-1479,italian,243 e. 58th st. (new york city),felidia (italian),243 e. 58th st. (212-758-1479)
16,fringale,san francisco,415-543-0573,french bistro,570 fourth st. (415-543-0573),fringale,570 fourth st. (415-543-0573)
17,carmines,new york city,212-362-2200,italian,2450 broadway (new york city),carmines,2450 broadway (212-362-2200)
18,brents deli,northridge,818-886-5679,delis,19565 parthenia ave.,brents deli (delis),19565 parthenia ave.
19,edison cafe,new york city,212-840-5000,diners,228 w. 47th st. (new york city),edison cafe,228 w. 47th st. (212-840-5000)
20,rex il ristorante,los angeles,213-627-2300,nuova cucina italian,617 s. olive st.,rex il ristorante,617 s. olive st.
21,bacchanalia,atlanta,404-365-0410,californian,3125 piedmont rd.,bacchanalia,3125 piedmont rd.
22,cafe flore,san francisco,415-621-8579,californian,2298 market st.,cafe flore (californian),2298 market st. (415-621-8579)
23,bakers cajun cafe,atlanta,404-223-5039,cajun/creole,1134 euclid ave. (atlanta),bakers cajun cafe,1134 euclid ave. (404-223-5039)
24,ciboulette restaurant,atlanta,404-874-7600,french (new),1529 piedmont ave. (404-874-7600),ciboulette restaurant,1529 piedmont ave. (404-874-7600)
25,carnegie deli,new york city,212-757-2245,delis,854 seventh ave. (212-757-2245),carnegie deli,854 seventh ave. (212-757-2245)
26,bradshaws restaurant,atlanta,404-261-7015,southern/soul,2911 s. pharr court,bradshaws restaurant,2911 s. pharr court
27,patina,los angeles,213-467-1108,californian,5955 melrose ave. (los angeles),patina,5955 melrose ave. (213-467-1108)

In [6]:
def CalcoloMatchingTable(TableL:pd.DataFrame,TableR:pd.DataFrame):

# Matching Methods: Qui si definiscono i Base Matcher da utilizzare; se ne possono aggiungere altri    
        SimTableA = lbm.levenshtein_label_based_similarity(TableL, TableR)
        # SimTableB = lbm.jaro_label_based_similarity(TableL, TableR)
        # SimTableB = vo.value_overlap_sim(GlobalSchema, Sources[y])
        SimTableB = vo.value_overlap_simjoin_jaccard(TableL, TableR, 0.6)

# Combined Approaches: qui si definisce il combiner; se ne possono aggiungere altri    
        # SimTable = ca.avg_sim_table([SimTableA,SimTableC])
        # SimTable = ca.min_sim_table([SimTableA,SimTableB,SimTableC])
        SimTable = ca.max_sim_table([SimTableA,SimTableB])

        # Weighted-sum
        #SimTable = ca.Weighted_sum([SimTableA,SimTableB,SimTableC], [.3,.4,.3] )

        
# Generating Correspondences: dalla tabella di similarità alle corrispondenze

### Local Single Attribute Strategies:
        MatchTable= lsa.thresholding(SimTable, 0.3)

        #MatchTable = lsa.top_K(SimTable,2,'A')
        #MatchTable = lsa.top_K(MatchTable,2,'B')

        
### Global Mapping (si usano solo questi due metodi)
        # MatchTable = gs.stable_marriage(MatchTable)
        # MatchTable = gs.simmetric_best_match(MatchTable)

        return MatchTable

In [7]:
def CalcoloLocalMatchingTable(Sources):
    LocalMatchingTable = pd.DataFrame(columns=['SOURCE_A', 'LAT_A', 'SOURCE_B', 'LAT_B', 'SLAT_A', 'SLAT_B', 'sim'])

    for x in Sources.keys():
        for y in Sources.keys():
            if (x < y):  

                LocalMatchingTableXY = CalcoloMatchingTable(Sources[x], Sources[y])

                print(x,y,len(LocalMatchingTableXY), end=" -- ")
                # si ottiene LocalMatchingTableXY , si rinominano gli attributi
                LocalMatchingTableXY.columns = ['LAT_A', 'LAT_B', 'sim']
                # si aggiungono i 2 nomi delle Local Sources matchate
                LocalMatchingTableXY['SOURCE_A'] = x
                LocalMatchingTableXY['SOURCE_B'] = y
                # e anche i SLAT
                LocalMatchingTableXY['SLAT_A'] = LocalMatchingTableXY['SOURCE_A'] + '_' + LocalMatchingTableXY['LAT_A']
                LocalMatchingTableXY['SLAT_B'] = LocalMatchingTableXY['SOURCE_B'] + '_' + LocalMatchingTableXY['LAT_B']
                # per poi aggiungerlo alla LocalMatchingTable complessiva
                LocalMatchingTable = LocalMatchingTable.append(LocalMatchingTableXY, sort=True)
    return LocalMatchingTable[['SOURCE_A', 'LAT_A', 'SOURCE_B', 'LAT_B', 'SLAT_A', 'SLAT_B', 'sim']]

In [8]:
def SchemaIntegration(Sources):

    LMT = CalcoloLocalMatchingTable(Sources)[['SLAT_A','SLAT_B']]
    
    GMT = si.GMTComponentiConnessi(LMT,Sources)
    

    return tdds.to_GMM(GMT)

In [14]:
GMT_Calcolata = tdds.to_GMT(SchemaIntegration(SOURCES))
GMT_Calcolata

S1 S2 8 --

   GAT SOURCE          LAT            SLAT
0    1     S1         city         S1_city
1    1     S2         city         S2_city
2    2     S1     telefone     S1_telefone
3    2     S1     location     S1_location
4    2     S2     telefono     S2_telefono
5    2     S2  descrizione  S2_descrizione
6    2     S2     location     S2_location
7    3     S1    name_type    S1_name_type
8    3     S1         name         S1_name
9    3     S2         nome         S2_nome
10   3     S2         type         S2_type
11   4     S1         addr         S1_addr
12   5     S2    indirizzo    S2_indirizzo

In [15]:
eval.Valuta(im.MatchIndottiGMT(GoldStandard),im.MatchIndottiGMT(GMT_Calcolata))

   MT  TP  FP  FN       P    R       F
0  11   5   6   5  0.4545  0.5  0.4762